### ISSUE TITLE
issue with trying to get it working on lambda 

### ISSUE THREAD

**Issue by ashleybeshir** [eredi93/lambda-git#12] opened 2018-11-11 21:14 UTC
Hello,

love this project as their isnt a alternative for git for python on lambdas. 
subprocess.call(["pip","install","lambda-git"]) this is used to install the module but when i try to import afterwards i get this error.

 "errorMessage": "[Errno 2] No such file or directory: '/var/task/vendor/git-2.4.3.tar'"

am i missing something ?

**Comment by eredi93** [comment] 2018-11-13 15:51
@ashleybeshir thanks for opening an issue. are you trying to run that `subprocess.call(["pip","install","lambda-git"])` in your lambda? can you give me more context?
i suggest you use something like http://apex.run or https://serverless.com you should have your dependencies as part of your lambda and not installing them at runtime

**Comment by mrthefastfender** [comment] 2018-11-15 14:00
Hi ered93,

I am trying to use your module and I am getting the same error. I used pip install to install dependencies in a folder together with my own code, zipped the folder, and uploaded it to Lambda, like I always do. 

[Errno 2] No such file or directory: '/var/task/vendor/git-2.4.3.tar'

**Comment by eredi93** [comment] 2018-11-15 14:56
@mrthefastfender can you share your lambda code?
i'm using it with [Apex](apex.run) and it works. unfortunately loading dependencies in lambda is a bit tricky due to the restricted permissions.
If you @mrthefastfender and @ashleybeshir could share a bit more info i could try to debug it.
if you could share a zip file of the lambda throwing that error i could check why is throwing that error

**Comment by mrthefastfender** [comment] 2018-12-21 12:49
The problem was, that the git binary was not included in the folder. I found a different solution using boto3 since I was trying to use CodeCommit.

**Comment by eredi93** [comment] 2018-12-22 19:43
I'm going to close this issue as i'm unable to reproduce the error. Once I have clear steps i can follow i'll reopen it.
@ashleybeshir how can you run `subprocess.call(["pip","install","lambda-git"])` when AWS Lambda doesn't let you call `pip`? 😕

**Comment by arsalazarjr** [comment] 2019-02-04 16:22
@ashleybeshir I just resolved the same issue. As mrthefastfender pointed out, the `vendor` folder isn't included in the pip install. I downloaded the git-2.4.3.tar file directly and included it in my lambda package. https://github.com/eredi93/lambda-git/blob/master/vendor/git-2.4.3.tar.

@eredi93 can you update the Python package so that when we run `pip install lambda-git`, it will include the vendor folder with required binary? Thanks.

**Comment by eredi93** [comment] 2019-02-05 13:49
thanks @arsalazarjr !! i found the issue.
https://github.com/eredi93/lambda-git/blob/f897734919330c518f43713fef6196c625f85960/setup.py#L27

`find_packages` only returns `git` and `tests`
```python
jacopo@moka:~/src/lambda-git|master
⇒  python
Python 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import find_packages
>>> find_packages()
['tests', 'git']
>>>
``` 
i'll update it now

**Closed** 2019-02-05 20:58 UTC

**Comment by eredi93** [comment] 2019-02-06 08:50
I just published a new version of the package
